server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: ${LOG_LEVEL_ROOT}

reviews:
  api:
    url: ${REVIEW_API_URL}
    key: ${REVIEW_API_KEY}
    items-per-page: ${REVIEWS_PER_PAGE}
